# Generated by Django 3.1.1 on 2020-09-14 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_opens',
            field=models.DateField(default=datetime.date(2020, 9, 14), verbose_name='When do you want the classroom to become available to students?'),
        ),
    ]
