# Generated by Django 3.1.1 on 2020-09-15 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20200914_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='classroom_closes',
        ),
        migrations.AddField(
            model_name='classroom',
            name='open_for_public',
            field=models.BooleanField(default=False, verbose_name='Can anyone sign up for this class?'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_opens',
            field=models.DateField(default=datetime.date(2020, 9, 15), verbose_name='When do you want the classroom to become available to students?'),
        ),
    ]
