# Generated by Django 3.1.1 on 2020-09-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_auto_20200915_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='open_for_public',
            field=models.BooleanField(default=False, verbose_name='Anyone can sign up for this class'),
        ),
    ]
