# Generated by Django 3.1.1 on 2020-09-20 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_auto_20200915_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='somecomapny', max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_name',
            field=models.CharField(default='classroom', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_opens',
            field=models.DateField(default=datetime.date(2020, 9, 20), verbose_name='When do you want the classroom to become available to students?'),
        ),
    ]
