# Generated by Django 3.1.1 on 2020-09-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_auto_20200920_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classrooms.company'),
        ),
    ]
