# Generated by Django 3.1.1 on 2020-09-23 17:56

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0007_classroom_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_name',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_opens',
            field=models.DateField(default=datetime.date(2020, 9, 23), verbose_name='When do you want the classroom to become available to students?'),
        ),
    ]
