# Generated by Django 3.1.1 on 2020-09-26 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0010_auto_20200924_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='how_many_weeks',
            field=models.PositiveIntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_opens',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When do you want the classroom to become available to students?'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ManyToManyField(default=4, to='classrooms.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
