# Generated by Django 3.1.1 on 2020-09-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='file_upload',
        ),
    ]
