# Generated by Django 3.1.1 on 2020-09-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0013_auto_20200928_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='file',
            name='week',
        ),
        migrations.CreateModel(
            name='FilePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
            ],
        ),
    ]
