# Generated by Django 3.1.1 on 2020-09-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0014_auto_20200929_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileplace',
            name='uploaded_file',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='classrooms.file'),
            preserve_default=False,
        ),
    ]
