# Generated by Django 3.1.1 on 2020-09-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0015_fileplace_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileplace',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='fileplace',
            name='uploaded_file',
            field=models.ManyToManyField(to='classrooms.File'),
        ),
        migrations.CreateModel(
            name='TopicDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
            ],
        ),
    ]
