# Generated by Django 3.1.1 on 2020-10-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0016_auto_20200930_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileplace',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='fileplace',
            name='uploaded_file',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='classrooms.file'),
            preserve_default=False,
        ),
    ]
