# Generated by Django 3.1.1 on 2020-10-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0017_auto_20201001_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicdescription',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='topicdescription',
            name='week',
        ),
        migrations.CreateModel(
            name='DescriptionPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.topicdescription')),
            ],
        ),
    ]
