# Generated by Django 3.1.1 on 2020-10-10 12:29

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0018_auto_20201001_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicdescription',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
