# Generated by Django 3.1.1 on 2020-10-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0020_videoplace_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(upload_to='teacher_uploads'),
        ),
        migrations.AlterField(
            model_name='videoplace',
            name='video_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.videos', verbose_name='Paste the Youtube Video ID here '),
        ),
    ]
