# Generated by Django 3.1.1 on 2020-10-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0021_auto_20201011_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(upload_to='media'),
        ),
    ]
