# Generated by Django 3.1.1 on 2020-10-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0022_auto_20201011_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileplace',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='fileplace',
            name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='videoplace',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='videoplace',
            name='video_link',
        ),
        migrations.AlterField(
            model_name='topicdescription',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='DescriptionPlace',
        ),
        migrations.DeleteModel(
            name='FilePlace',
        ),
        migrations.DeleteModel(
            name='VideoPlace',
        ),
        migrations.AddField(
            model_name='file',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classrooms.week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicdescription',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classrooms.week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classrooms.week'),
            preserve_default=False,
        ),
    ]
