# Generated by Django 3.1.1 on 2020-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0024_auto_20201012_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='finished_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
