# Generated by Django 3.1.1 on 2020-10-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0025_week_finished_or_not'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='finished_or_not',
            new_name='finished',
        ),
    ]
