# Generated by Django 3.1.1 on 2020-10-18 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0026_auto_20201017_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='classroom_opens',
        ),
        migrations.AddField(
            model_name='classroom',
            name='how_many_times',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator], verbose_name='How many times a week?'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='how_many_weeks',
            field=models.PositiveIntegerField(default=32, verbose_name='How many classes?'),
        ),
    ]
