# Generated by Django 3.1.1 on 2020-10-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0027_auto_20201018_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='classroom_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='name',
        ),
    ]
